export const CREATE_COURSE = 'CREATE_COURSE';
//course apiCourse
export const COURSE_LOADING = 'COURSE_LOADING';
export const COURSE_SUCCESS = 'COURSE_SUCCESS';
export const COURSE_ERROR = 'COURSE_ERROR';
export const COURSE_UPDATE = 'COURSE_UPDATE';

//authore api
export const COURSE_AUTHORE_LOAIDNG = 'COURSE_AUTHORE_LOAIDNG';
export const COURSE_AUTHORE_SUCCESS = 'COURSE_AUTHORE_SUCCESS';
export const COURSE_AUTHORE_ERROR = 'COURSE_AUTHORE_ERROR';
